theme: jekyll-theme-cayman
title: Satoshi Miyazawa
description: I am a Project Researcher at Center for Spatial Information Science, the University of Tokyo, Japan. My work focuses on on city-scale human mobility prediction with GPS and SNS.